version: "3.8"
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    ports:
      - "5276:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mariadb-network
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    networks:
      - mariadb-network
    ports:
      - "4031:80"
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb
networks:
  mariadb-network:
volumes:
  db_data:
